### ISSUE TITLE
Initial Run stuck at Status is Unreconized status

### ISSUE THREAD

**Issue by elric667** [zcalusic/dockerfiles#7]
Status: Downloaded newer image for zcalusic/pcloud:latest
pCloud console client v.2.0.1
Down: Everything Downloaded| Up: Everything Uploaded, status is LOGIN_REQUIRED
Please, enter password
logging in
Down: Everything Downloaded| Up: Everything Uploaded, status is CONNECTING
Down: Everything Downloaded| Up: Everything Uploaded, status is Unrecognized status

This is the command I ran to build the container

sudo docker run -it \
     --privileged \
     -v pcloud-cache-dir:/volume1/docker/pcloud \
     --name pcloud \
     zcalusic/pcloud \
     pcloudcc -u (redacted) -s -m pcloud-mount-dir

**Comment by zcalusic** [comment]
It seems you misunderstood how to properly mount host volume inside container. pcloud-cache-dir is to be replaced with an existing HOST folder. That /root/.pcloud folder is NOT to be changed. Also pcloud-mount-dir is to be replaced with some existing folder INSIDE cointainer, say /mnt.

Please fix those then try again.

**Comment by elric667** [comment]
sudo docker run -it \
>      --privileged \
>      -v pcloud-cache-dir:/root/.pcloud \
>      --name pcloud \
>      zcalusic/pcloud \
>      pcloudcc -u <redacted> -s -m pcloud-mount-dir
pCloud console client v.2.0.1
Down: Everything Downloaded| Up: Everything Uploaded, status is CONNECTING
Down: Everything Downloaded| Up: Everything Uploaded, status is Unrecognized status

**Comment by elric667** [comment]
Got past this problem
